Repository terraform-providers/terraform-provider-mysql, pull requests merged in 2018-10, with the labels that each got.

#15 Updating database and user docs
  website/docs/r/database.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation

#39 Support mysql_grant table
  mysql/resource_grant.go
  mysql/resource_grant_test.go
Labels: enhancement, size/XS

#43 Switch to lazy connections to MySQL and add TLS configuration support to the provider
  .gitignore
  CHANGELOG.md
  mysql/provider.go
  mysql/resource_database.go
  mysql/resource_database_test.go
  mysql/resource_grant.go
  mysql/resource_grant_test.go
  mysql/resource_user.go
  mysql/resource_user_test.go
  website/docs/index.html.markdown
  website/docs/r/database.html.markdown
  website/docs/r/grant.html.markdown
  website/docs/r/user.html.markdown
Labels: bug, enhancement, provider, size/XL, technical-debt

#45 Allow wildcards on GRANT statements by escaping database names
  mysql/resource_grant.go
Labels: bug, size/XS

#49 Set AllowNativePasswords to true to get tests working again
  README.md
  mysql/provider.go
  mysql/resource_grant.go
Labels: bug, crash, size/XS, technical-debt

#51 Add SOCKS5 proxy support.
  GNUmakefile
  go.mod
  mysql/provider.go
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: documentation, enhancement, size/XL
