Repository terraform-providers/terraform-provider-mysql, pull requests merged in 2019-11, with the labels that each got.

#105 feat: 🎸 enable setting allow cleartext password flag
  mysql/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#102 Add proxy argument
  mysql/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#106 Prep Changelog for v1.9.0 release
  CHANGELOG.md
Labels: size/XS
