Repository terraform-providers/terraform-provider-mysql, pull requests merged in 2019-06, with the labels that each got.

#84 Update user argument on grant docs
  website/docs/r/grant.html.markdown
Labels: documentation, size/XS

#81 Update user_password.html.markdown
  website/docs/r/user_password.html.markdown
Labels: documentation, size/XS

#83 Add compatibility to create databases on mariadb instances
  mysql/provider.go
  mysql/resource_database.go
Labels: size/XS

#69 Consider replacing satori/go.uuid
  go.mod
  go.sum
  mysql/resource_user_password.go
  vendor/github.com/gofrs/uuid/.gitignore
  vendor/github.com/gofrs/uuid/.travis.yml
  vendor/github.com/gofrs/uuid/LICENSE
  vendor/github.com/gofrs/uuid/README.md
  vendor/github.com/gofrs/uuid/codec.go
  vendor/github.com/gofrs/uuid/fuzz.go
  vendor/github.com/gofrs/uuid/generator.go
  vendor/github.com/gofrs/uuid/sql.go
  vendor/github.com/gofrs/uuid/uuid.go
  vendor/github.com/satori/go.uuid/.travis.yml
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/generator.go
  vendor/modules.txt
Labels: dependencies, size/XXL
